const ACTIONS = {
  CREATE_GROUP_REQ: 'CREATE_GROUP_REQ',
  CREATE_GROUP_SUCCESS: 'CREATE_GROUP_SUCCESS',
  CREATE_GROUP_FAILURE: 'CREATE_GROUP_FAILURE',

  GROUP_LIST_REQ: 'GROUP_LIST_REQ',
  GROUP_LIST_SUCCESS: 'GROUP_LIST_SUCCESS',
  GROUP_LIST_FAILURE: 'GROUP_LIST_FAILURE',

  GET_ALL_USERS_REQ: 'GET_ALL_USERS_REQ',
  GET_ALL_USERS_SUCCESS: 'GET_ALL_USERS_SUCCESS',
  GET_ALL_USERS_FAILIURE: 'GET_ALL_USERS_FAILIURE',
};

export default ACTIONS;
