const ACTIONS = {
  SIGNIN_REQ: 'SIGNIN_REQ',
  SIGNIN_SUCCESS: 'SIGNIN_SUCCESS',
  SIGNIN_FAILURE: 'SIGNIN_FAILURE',

  SIGNUP_REQ: 'SIGNUP_REQ',
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  SIGNUP_FAILURE: 'SIGNUP_FAILURE',

  SIGNOUT_REQ: 'SIGNOUT_REQ',
  SIGNOUT_SUCCESS: 'SIGNOUT_SUCCESS',
  SIGNOUT_FAILURE: 'SIGNOUT_FAILURE',
};

export default ACTIONS;
