const ACTIONS = {
  SIGNIN_REQ: 'SIGNIN_REQ',
  SIGNIN_SUCCESS: 'SIGNIN_SUCCESS',
  SIGNIN_FAILURE: 'SIGNIN_FAILURE',

  SIGNOUT_REQ: 'SIGNOUT_REQ',
  SIGNOUT_SUCCESS: 'SIGNOUT_SUCCESS',
  SIGNOUT_FAILURE: 'SIGNOUT_FAILURE',
};

export default ACTIONS;
